/** @type {import('@lhci/cli').Config} */
export default {
	ci: {
		collect: {
			staticDistDir: './dist',
			url: ['/', '/about/', '/contact/'],
			numberOfRuns: 3,
		},
		assert: {
			preset: 'lighthouse:no-pwa',
			assertions: {
				// カテゴリスコア（CI環境では閾値を緩和）
				'categories:performance': ['warn', { minScore: 0.5 }],
				'categories:accessibility': ['error', { minScore: 0.9 }],
				'categories:best-practices': ['warn', { minScore: 0.8 }],
				'categories:seo': ['warn', { minScore: 0.9 }],
				// 個別アサーションを全てoff
				'first-contentful-paint': 'off',
				'largest-contentful-paint': 'off',
				interactive: 'off',
				'max-potential-fid': 'off',
				'cumulative-layout-shift': 'off',
				'speed-index': 'off',
				'total-blocking-time': 'off',
				'render-blocking-resources': 'off',
				'render-blocking-insight': 'off',
				'unused-css-rules': 'off',
				'unused-javascript': 'off',
				'unminified-css': 'off',
				'unminified-javascript': 'off',
				'modern-image-formats': 'off',
				'uses-optimized-images': 'off',
				'uses-responsive-images': 'off',
				'offscreen-images': 'off',
				'uses-text-compression': 'off',
				'uses-rel-preconnect': 'off',
				'server-response-time': 'off',
				redirects: 'off',
				'uses-long-cache-ttl': 'off',
				'total-byte-weight': 'off',
				'dom-size': 'off',
				'dom-size-insight': 'off',
				'critical-request-chains': 'off',
				'network-requests': 'off',
				'network-rtt': 'off',
				'network-server-latency': 'off',
				'main-thread-tasks': 'off',
				'bootup-time': 'off',
				'mainthread-work-breakdown': 'off',
				'font-display': 'off',
				'network-dependency-tree-insight': 'off',
				'prioritize-lcp-image': 'off',
				'layout-shifts': 'off',
				'long-tasks': 'off',
				'layout-shift-elements': 'off',
				'lcp-lazy-loaded': 'off',
				'bf-cache': 'off',
			},
		},
		upload: {
			target: 'temporary-public-storage',
		},
	},
};
